### ISSUE TITLE
Bashisms

### ISSUE THREAD

**Issue by ghost** [cygwinports/icu#1]
This syntax:

~~~
${VERSION//./_}
~~~

http://github.com/cygwinports/icu/blob/f408a23/icu.cygport#L13

Is a Bashism and is not portable:

http://mywiki.wooledge.org/Bashism#Parameter_Expansions

I would be interested to correct these if you are open to it

**Comment by yselkowitz** [comment]
cygport is not (nor meant to be) portable to shells other than bash.
